const router = require('express').Router();
const { verifyToken, requireRoles, requireVerifiedEmail } = require('../middleware/authMiddleware');
const { upload, MAX_FILE_SIZE, MAX_FILE_MB } = require('../middleware/uploads');
const { getBranches, getAllResources, getResourceById, deleteResource, rateResource, uploadResource, getRecommendedResources, downloadResource } = require('../controllers/resourceController');
router.get('/upload-config', (req, res) => res.json({ maxFileBytes: MAX_FILE_SIZE, maxFileMB: MAX_FILE_MB, extensions: ['pdf', 'docx', 'pptx'], fileUploadsEnabled: Boolean(process.env.FIREBASE_STORAGE_BUCKET) }));
router.get('/branches', getBranches);
router.get('/recommended', getRecommendedResources);
router.get('/', getAllResources);
router.get('/:id/file', downloadResource);
router.get('/:id', getResourceById);
router.post('/upload-resource', verifyToken, requireRoles('Faculty', 'Admin'), requireVerifiedEmail, upload.single('file'), uploadResource);
router.delete('/:id', verifyToken, requireRoles('Faculty', 'Admin'), deleteResource);
router.post('/:id/rate', verifyToken, requireVerifiedEmail, rateResource);
module.exports = router;
