const router = require('express').Router();
const { verifyToken, requireRoles, requireVerifiedEmail } = require('../middleware/authMiddleware');
const { upload } = require('../middleware/uploads');
const { getBranches, getAllResources, getResourceById, deleteResource, rateResource, uploadResource, getRecommendedResources, downloadResource } = require('../controllers/resourceController');
router.get('/branches', getBranches);
router.get('/recommended', getRecommendedResources);
router.get('/', getAllResources);
router.get('/:id/file', downloadResource);
router.get('/:id', getResourceById);
router.post('/upload-resource', verifyToken, requireRoles('Faculty', 'Admin'), requireVerifiedEmail, upload.single('file'), uploadResource);
router.delete('/:id', verifyToken, requireRoles('Faculty', 'Admin'), deleteResource);
router.post('/:id/rate', verifyToken, requireVerifiedEmail, rateResource);
module.exports = router;
